HAI 1.2

OBTW
    FIBONACCI, IN CAT
    ==================
    ASKS 4 N. PRINTS DA N'TH FIBONACCI NUMBR.
    FIB(0) IZ 0, FIB(1) IZ 1, FIB(10) IZ 55.
    SRS BIZNESS. NO KITTEHS WERE HARMED.
TLDR

BTW    FURST WE INTERROGATE DA HOOMAN
VISIBLE "N? "!
I HAS A n
GIMMEH n
n IS NOW A NUMBR

BTW    HOOMANZ IZ SNEAKY AN TYPE NEGATIVE NUMBRZ. WE SAY NO.
BTW    DIFFRINT n AN BIGGR OF n AN 0   MEANZ   n IZ NOT MAX(n, 0)   MEANZ   n < 0
DIFFRINT n AN BIGGR OF n AN 0
O RLY?
    YA RLY
        BTW    UR NEGATIVE NUMBR IZ IN ANOTHER CASTLE
        n R 0
OIC

BTW    a IZ DA ONE WE WANT. b IZ ALWAYZ ONE RUNG AHEAD.
I HAS A a ITZ 0
I HAS A b ITZ 1
I HAS A nxt ITZ 0
I HAS A i ITZ 0

BTW    UP DA LADDER, N TIMEZ. TIL CHECKS B4 EACH RUNG,
BTW    SO N = 0 CLIMBS NUFFIN AN a STAYZ 0. PURRFECT.
IM IN YR ladder UPPIN YR i TIL BOTH SAEM i AN n
    nxt R SUM OF a AN b
    a R b
    b R nxt
IM OUTTA YR ladder

VISIBLE a

KTHXBYE
