HAI 1.2

OBTW
    HELLO WORLD, IN CAT
    ====================
    DA CLASSIC. BUT A BARE VISIBLE "HELLO, WORLD!" IZ NO FUN,
    SO WE BILD DA STRING OUTTA PIECES WIF SMOOSH, AN LERN
    SUMTHIN ABOUT LOLCODE WHILE WE R AT IT.
TLDR

BTW    YR VARIABLZ. STRINGZ IZ CALLD YARN IN DIS LANGUAGE.
I HAS A greetin ITZ "Hello"
I HAS A subjekt ITZ "World"

BTW    SMOOSH GLUEZ YARNZ TOGETHR. MKAY ENDZ DA LIST,
BTW    COZ SMOOSH TAKEZ AS MANY ARGZ AS U LIKE.
I HAS A wurdz ITZ SMOOSH greetin ", " subjekt "!" MKAY

BTW    VISIBLE PRINTZ AN ADDZ A NEWLINE. A TRAILIN "!" WUD SUPPRESS IT.
VISIBLE wurdz

KTHXBYE
